#环境与源码
name: Setup
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: LineageOS/android_kernel_xiaomi_sdm845
          ref: lineage-21
          submodules: recursive

      - name: Install tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            make bc bison flex libssl-dev \
            aarch64-linux-android-14.0  # 所有工具集中安装

      - name: Cache environment
        uses: actions/cache@v3
        with:
          path: |
            /usr/bin/aarch64-linux-android-*
            .
          key: ${{ runner.os }}-env-${{ github.sha }}
